### PR TITLE
Change color scheme for focused / hovered elements

### LINKED ISSUE #199: Differentiate `:hover` and `:selected`
Differentiate `:hover` and `:selected` in dropdown so that they don't look the same

colorthesame

### PR DESCRIPTION
**Pull request by pierreTklein**
## Screenshot

image

### CODE REVIEW

**Comment by erickzhao** [comment]
this is p sexy

**Comment by loreina** [comment]
For pill box selectors, will it always be `primaryLight` even though the `selected` is no longer listed once selected?

image

**Comment by loreina** [comment]
Also this might be a separate issue but when selected, shirt size stays `white`?

image

**Comment by erickzhao** [comment]
>For pill box selectors, will it always be primaryLight even though the selected is no longer listed once selected?

I like that.

> Also this might be a separate issue but when selected, shirt size stays white?

I imagine because it's a not a multi-select, so it doesn't need the pills.

**Comment by loreina** [comment]
re: shirt size

Not that it needs the pills, but shouldn't `M` be selected in red like how the selected in the job question is red even though there are limited options?

**Comment by pierreTklein** [comment]
I honestly don't know what is different between the creatableSelect and the Select classes... they have the exact same styling :'(

**Comment by loreina** [comment]
Let's merge with known bug and make an issue we can come back to later lmao

**Pull request merged**
