### PR TITLE
Add code formatting with Prettier

### LINKED ISSUE #187: Uniformize code formatting
Reference: https://github.com/sw-yx/react-typescript-cheatsheet#prettier--tslint

Prettier ([see on GitHub](https://github.com/prettier/prettier)) is a widely-used tool to format code. I think it would be very useful to get it set up because at the moment, our code style is very disorganized. Enabling Prettier and having it hooked to VS Code on save would be a step in the right direction to make our code neater and also avoid having minor style changes in every PR.

### PR DESCRIPTION
**Pull request by loreina**
Add Prettier config and dependencies for better code formatting for `.ts` and `.tsx`.

Closes #187 

Options: https://prettier.io/docs/en/options.html

Thoughts:
- I used `"singleQuote": true` but in some files, we have double quotes. I'm not sure how that'll affect those/if the double quotes are necessary? If yes, I'll change to `false`.
- How do we want to config `arrowParens`? Read in options link.

To enable Pretter in VS Code:
1. Download the [extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
2. Add `"editor.formatOnSave": true` to workspace settings.

Note: We should add the `npm run lint` to deployment scripts in case someone isn't using VS Code to auto format or isn't using auto format.

Also relates to #175, we should include a setup for VS Code in the README.

### CODE REVIEW

**Comment by pierreTklein** [comment]
I would prefer  `always` for arrow links

**Comment by loreina** [comment]
@erickzhao should we wait for #176 to be merged before merging this one? 

After this goes through, we should probably do another PR with all the files reformatted with this config

**Comment by loreina** [comment]
@erickzhao should we wait for #176 to be merged before merging this one?

After this goes through, we'll probably have another PR with all files reformatted with this config

**Comment by erickzhao** [comment]
>@erickzhao should we wait for #176 to be merged before merging this one?

I think so. 

> After this goes through, we'll probably have another PR with all files reformatted with this config

Definitely! Also maybe add Travis back in to make sure unlinted code doesn't get PRed.

**Comment by erickzhao** [comment]
@hackmcgill/dev @hackmcgill/directors 

As an aside, can we agree to have these options enabled to TRUE?

image

Motivation: https://robots.thoughtbot.com/no-newline-at-end-of-file

**Comment by loreina** [comment]
Added folder-specific vs code settings. Downside to this is that it's forced on anyone who clones/works on the repo. Upside is auto formatting?

Can't force extensions to be downloaded but at the very least, they can show up as recommended extensions 🤷‍♀️

**Pull request merged**
