### PR TITLE
Refactor/164 extract toast notifications

### LINKED ISSUE #164: Wrap Toaster notifications globally
Currently, we're wrapping the Toaster HOC around individual routes.

This works *okay* for our purposes, but it would be cleaner and simpler to wrap it around the entire app. This would help us in a few ways:

* Simpler app structure: no need to wrap the HOC around individual routes.
* Allows notifications to sustain across pages (avoids situations like #91 caused by rendering a Toast notification on a page that is no longer being rendered).

### PR DESCRIPTION
**Pull request by pierreTklein**
Revives PR #166, and closes #164

### CODE REVIEW

**Comment by pierreTklein** [comment]
Note that a side-effect of removing `mt: 50` is that everything is now 50px higher... 

image

**Comment by pierreTklein** [comment]
@erickzhao what do we do about the height issue?

**Comment by loreina** [comment]
cards look kind of weird when they're that close to status

**Comment by pierreTklein** [comment]
@loreina 
> cards look kind of weird when they're that close to status

This PR does not change the distance between status and the cards. What this does is move both status and cards closer to the top of the window

**Comment by loreina** [comment]
The spacing is still weird, I think it might be bc it was closer to the triplexes before and now its not?

**Comment by pierreTklein** [comment]
Yeah, most likely.

**Pull request merged**
