### PR TITLE
Refactor/78 shared import

### LINKED ISSUE #78: Simplify import API for components
Currently, we use a lot of custom components to accomplish many things. This means that our imports on top of files get very cluttered.

I'm proposing that for the `shared`, `components`, and `containers` folders, we have an `index.js` file that exports all the components so that we can have cleaner imports when we use stuff.

Example:
```javascript
import { H1, H2, Paragraph } from `src/shared/`;
```

### PR DESCRIPTION
**Pull request by pierreTklein**
# Simplification of imports by creating `index.ts` files. 

## Fixes #78

Used https://github.com/bencoveney/barrelsby to generate index.ts files.

## Directories refactored:

- Auth
- Config
- Shared

## Directories not refactored:

- Container
- Assets
- Componen

### CODE REVIEW

**Comment by erickzhao** [comment]
@pierreTklein this is beautiful

but also can we wait until #176 is merged before doing this process? I imagine there are going to be a lot of merge conflicts from the absolute paths.

**Comment by pierreTklein** [comment]
Sounds good, let's get that other PR in

**Comment by erickzhao** [comment]
@pierreTklein I'll get the final config change done after my final tomorrow.

**Comment by pierreTklein** [comment]
@erickzhao can I merge this?

**Pull request merged**
