### PR TITLE
Delete .travis.yml

### LINKED ISSUE #204: Remove TravisCI
Since we are using Netlify now, we should remove the TravisCI files from the repo.

### PR DESCRIPTION
**Pull request by krubenok**
Pretty straight forward. /shrug

Closes #204

### CODE REVIEW

**Comment by erickzhao** [comment]
We might want to keep it for #201

**Comment by loreina** [comment]
heck

**Comment by krubenok** [comment]
@erickzhao, is this so that we can run CI tests on the #201 stuff? We can do that with Netlify too.

**Comment by erickzhao** [comment]
@krubenok yep. If we can do it with Netlify sounds good to me.

**Comment by krubenok** [comment]
https://www.netlify.com/docs/netlify-toml-reference/

Reference docs on the file here!  @loreina @erickzhao

**Pull request merged**
