### PR TITLE
Add max character counts to textarea input

### LINKED ISSUE #200: Cap the input fields at a max length
Users can input infinite chars which could take up all of storage.

screen shot 2018-12-14 at 1 42 55 am

### PR DESCRIPTION
**Pull request by pierreTklein**
## When input is in box:
image

## When no input is in box:
image

### CODE REVIEW

**Comment by pierreTklein** [comment]
charararararacters

**Comment by pierreTklein** [comment]
image

**Comment by pierreTklein** [comment]
Known bug:
image

**Comment by loreina** [comment]
@pierreTklein do you want to make a separate issue for the checkbox and merge this?

**Comment by pierreTklein** [comment]
Sure. We merge and then create an issue for it or something.

**Pull request merged**
